In [12]:
import numpy as np

In [13]:
import numpy as np
a=np.array([1,1,5]); dtypes='int16'
print(a)

[1 1 5]


In [14]:
b=np.array([[1.0,2.0,3.0],[6.0,7.0,8.0]])
print(b)

[[1. 2. 3.]
 [6. 7. 8.]]


In [15]:
a.ndim

1

In [16]:
b.shape

(2, 3)

In [17]:
a.dtype

dtype('int64')

In [18]:
a.nbytes

24

In [19]:
a.itemsize

8

In [20]:
c =np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
c [1,5]


np.int64(13)

In [22]:
c [:,4]

array([ 5, 12])

In [23]:
c [1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [24]:
c [0,5:1:-1]

array([6, 5, 4, 3])

In [25]:
c [1,6]=20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 20]]


In [26]:
c [1,:]=5
print(c)

[[1 2 3 4 5 6 7]
 [5 5 5 5 5 5 5]]


In [27]:
c [:,3]=9
print(c)

[[1 2 3 9 5 6 7]
 [5 5 5 9 5 5 5]]


In [28]:
d =np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
d [0,1,1]

np.int64(4)

In [30]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones([4,1,1])

array([[[1.]],

       [[1.]],

       [[1.]],

       [[1.]]])

In [32]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [33]:
np.full(c.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [34]:
np.random.rand(4,2,3)

array([[[0.9506619 , 0.97034714, 0.87937333],
        [0.03612312, 0.60367193, 0.2942648 ]],

       [[0.01882166, 0.71571664, 0.80635583],
        [0.91607513, 0.30032399, 0.47614125]],

       [[0.27392625, 0.9165863 , 0.15443659],
        [0.68957276, 0.50531443, 0.82800841]],

       [[0.65135473, 0.38390503, 0.56084916],
        [0.01618677, 0.77922784, 0.32221947]]])

In [35]:
np.random.randint(7,size=(3,3))

array([[0, 6, 6],
       [3, 2, 1],
       [6, 5, 5]])

In [36]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
arr =np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


pratice problem

In [38]:
#pratice problem
e=np.full((5,5),1)

print(e)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [39]:
e[1,1:4:1]=0
e[3,1:4:1]=0
e[2,1:4:2]=0
e[2,2]=9
print(e)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


over

In [41]:
import numpy as np
g = np.array([1,2,3])
b=g
print(a)
b=[1,2,2]

[1 1 5]


In [46]:
z+y

array([ 6,  8, 10, 12, 14])

In [47]:
z-y

array([-4, -4, -4, -4, -4])

In [48]:
z/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [49]:
z

array([1, 2, 3, 4, 5])

In [50]:
y

array([5, 6, 7, 8, 9])

In [51]:
z*y

array([ 5, 12, 21, 32, 45])

In [52]:
z**2

array([ 1,  4,  9, 16, 25])

In [53]:
np.cos(z)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [54]:
np.tan(y)

array([-3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [ ]:
#  linear algebera